apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  annotations:
    kubernetes.io/ingress.class: traefik-private
spec:
  entryPoints:
  - http-private
  routes:
  - match: Host(`argocd.internal.lainecloud.com`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-webhook
  annotations:
    kubernetes.io/ingress.class: traefik-private
spec:
  entryPoints:
  - http-public
  routes:
  - match: Host(`argocd.lainecloud.com`) && PathPrefix(`/api/webhook`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80

