apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/phillebaba/manifests//traefik/base
nameSuffix: -private
configMapGenerator:
  - name: traefik-conf
    behavior: replace
    files:
      - traefik.toml
